/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shapes;

import java.awt.Color;
import java.awt.Point;
import javax.swing.JColorChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class RectangleDialog extends javax.swing.JFrame implements Node {

    /**
     * Creates new form RectangleDialog
     */
    Node parent;
    Rectangle r;
    DrawingEngineA canvas;
    Color borderColor=Color.BLACK,fillColour=Color.BLACK;
    PaintApplicationWindow w=new PaintApplicationWindow();
    public RectangleDialog(DrawingEngineA canvas,PaintApplicationWindow w) {
        this.canvas=canvas;
        this.w=w;
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        insert = new javax.swing.JButton();
        fillColor = new javax.swing.JButton();
        color = new javax.swing.JButton();
        xCoordinate = new javax.swing.JTextField();
        yCoordinate = new javax.swing.JTextField();
        length = new javax.swing.JTextField();
        width = new javax.swing.JTextField();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Rectangle Properties");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("X Coordinate");

        jLabel2.setText("Y Coordinate");

        jLabel3.setText("Length");

        jLabel4.setText("Width");

        insert.setBackground(new java.awt.Color(0, 0, 0));
        insert.setForeground(new java.awt.Color(255, 255, 255));
        insert.setText("Create Rectangle");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        fillColor.setBackground(new java.awt.Color(0, 0, 0));
        fillColor.setForeground(new java.awt.Color(255, 255, 255));
        fillColor.setText("Fill Color");
        fillColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillColorActionPerformed(evt);
            }
        });

        color.setBackground(new java.awt.Color(0, 0, 0));
        color.setForeground(new java.awt.Color(255, 255, 255));
        color.setText("Border color");
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });

        xCoordinate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xCoordinateActionPerformed(evt);
            }
        });

        length.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(xCoordinate)
                                    .addComponent(yCoordinate)
                                    .addComponent(length)
                                    .addComponent(width)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(color)
                                .addGap(18, 18, 18)
                                .addComponent(fillColor))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(insert)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(xCoordinate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(yCoordinate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(length, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(width, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(color)
                    .addComponent(fillColor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insert)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xCoordinateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xCoordinateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xCoordinateActionPerformed

    private void lengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lengthActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // TODO add your handling code here:
        try{
            if(width.getText().equals("")||length.getText().equals("")|xCoordinate.getText().equals("")||yCoordinate.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null,"Some fields are empty");
                if(width.getText().equals(""))
                    width.setText("Add data here");
                if(length.getText().equals(""))
                    length.setText("Add data here");
                if(xCoordinate.getText().equals(""))
                    xCoordinate.setText("Add data here");
                if(yCoordinate.getText().equals(""))
                    yCoordinate.setText("Add data here");
                
            }
            else{ 
             if(Integer.parseInt(width.getText())<=0||Integer.parseInt(length.getText())<=0||Integer.parseInt(xCoordinate.getText())<0||Integer.parseInt(yCoordinate.getText())<0)
                JOptionPane.showMessageDialog(null,"Please enter a positive number");
             else{
             r=new Rectangle(new Point(Integer.parseInt(xCoordinate.getText()),Integer.parseInt(yCoordinate.getText())),Integer.parseInt(width.getText()),Integer.parseInt(length.getText()));    
             r.setColor(borderColor);
             r.setFillColor(fillColour);
             canvas.addShape(r);
             w.setComboBox(3);
             setVisible(false);
             ((JFrame)getParentNode()).setVisible(true);}
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Please check the data entered");
        }
    }//GEN-LAST:event_insertActionPerformed

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        // TODO add your handling code here:
        borderColor=JColorChooser.showDialog(null, "Choose color", Color.black);
        if(borderColor==null)
            borderColor=Color.BLACK;
    }//GEN-LAST:event_colorActionPerformed

    private void fillColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillColorActionPerformed
        // TODO add your handling code here:
        fillColour=JColorChooser.showDialog(null, "Choose fill color", Color.WHITE);
        if(fillColour==null)
            fillColour=Color.BLACK;

    }//GEN-LAST:event_fillColorActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
               this.setVisible(false);
        ((JFrame)getParentNode()).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    @Override
    public Node getParentNode() {
        return parent;
    }

    @Override
    public void setParentNode(Node node) {
        parent=node;
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton color;
    private javax.swing.JButton fillColor;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField length;
    private javax.swing.JTextField width;
    private javax.swing.JTextField xCoordinate;
    private javax.swing.JTextField yCoordinate;
    // End of variables declaration//GEN-END:variables
}
